export const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const countryAbbreviations = {
  af: "Afghanistan",
  al: "Albania",
  dz: "Algeria",
  ad: "Andorra",
  ao: "Angola",
  ag: "Antigua and Barbuda",
  ar: "Argentina",
  am: "Armenia",
  au: "Australia",
  at: "Austria",
  az: "Azerbaijan",
  bs: "Bahamas",
  bh: "Bahrain",
  bd: "Bangladesh",
  bb: "Barbados",
  by: "Belarus",
  be: "Belgium",
  bz: "Belize",
  bj: "Benin",
  bt: "Bhutan",
  bo: "Bolivia",
  ba: "Bosnia and Herzegovina",
  bw: "Botswana",
  br: "Brazil",
  bn: "Brunei",
  bg: "Bulgaria",
  bf: "Burkina Faso",
  bi: "Burundi",
  cv: "Cabo Verde",
  kh: "Cambodia",
  cm: "Cameroon",
  ca: "Canada",
  cf: "Central African Republic",
  td: "Chad",
  cl: "Chile",
  cn: "China",
  co: "Colombia",
  km: "Comoros",
  cd: "Congo, Democratic Republic of the",
  cg: "Congo, Republic of the",
  cr: "Costa Rica",
  hr: "Croatia",
  cu: "Cuba",
  cy: "Cyprus",
  cz: "Czech Republic",
  dk: "Denmark",
  dj: "Djibouti",
  dm: "Dominica",
  do: "Dominican Republic",
  ec: "Ecuador",
  eg: "Egypt",
  sv: "El Salvador",
  gq: "Equatorial Guinea",
  er: "Eritrea",
  ee: "Estonia",
  sz: "Eswatini",
  et: "Ethiopia",
  fj: "Fiji",
  fi: "Finland",
  fr: "France",
  ga: "Gabon",
  gm: "Gambia",
  ge: "Georgia",
  de: "Germany",
  gh: "Ghana",
  gr: "Greece",
  gd: "Grenada",
  gt: "Guatemala",
  gn: "Guinea",
  gw: "Guinea-Bissau",
  gy: "Guyana",
  ht: "Haiti",
  hn: "Honduras",
  hu: "Hungary",
  is: "Iceland",
  in: "India",
  id: "Indonesia",
  ir: "Iran",
  iq: "Iraq",
  ie: "Ireland",
  il: "Israel",
  it: "Italy",
  jm: "Jamaica",
  jp: "Japan",
  jo: "Jordan",
  kz: "Kazakhstan",
  ke: "Kenya",
  ki: "Kiribati",
  kp: "Korea, North",
  kr: "Korea, South",
  xk: "Kosovo",
  kw: "Kuwait",
  kg: "Kyrgyzstan",
  la: "Laos",
  lv: "Latvia",
  lb: "Lebanon",
  ls: "Lesotho",
  lr: "Liberia",
  ly: "Libya",
  li: "Liechtenstein",
  lt: "Lithuania",
  lu: "Luxembourg",
  mg: "Madagascar",
  mw: "Malawi",
  my: "Malaysia",
  mv: "Maldives",
  ml: "Mali",
  mt: "Malta",
  mh: "Marshall Islands",
  mr: "Mauritania",
  mu: "Mauritius",
  mx: "Mexico",
  fm: "Micronesia",
  md: "Moldova",
  mc: "Monaco",
  mn: "Mongolia",
  me: "Montenegro",
  ma: "Morocco",
  mz: "Mozambique",
  mm: "Myanmar",
  na: "Namibia",
  nr: "Nauru",
  np: "Nepal",
  nl: "Netherlands",
  nz: "New Zealand",
  ni: "Nicaragua",
  ne: "Niger",
  ng: "Nigeria",
  mk: "North Macedonia",
  no: "Norway",
  om: "Oman",
  pk: "Pakistan",
  pw: "Palau",
  ps: "Palestine",
  pa: "Panama",
  pg: "Papua New Guinea",
  py: "Paraguay",
  pe: "Peru",
  ph: "Philippines",
  pl: "Poland",
  pt: "Portugal",
  qa: "Qatar",
  ro: "Romania",
  ru: "Russia",
  rw: "Rwanda",
  kn: "Saint Kitts and Nevis",
  lc: "Saint Lucia",
  vc: "Saint Vincent and the Grenadines",
  ws: "Samoa",
  sm: "San Marino",
  st: "Sao Tome and Principe",
  sa: "Saudi Arabia",
  sn: "Senegal",
  rs: "Serbia",
  sc: "Seychelles",
  sl: "Sierra Leone",
  sg: "Singapore",
  sk: "Slovakia",
  si: "Slovenia",
  sb: "Solomon Islands",
  so: "Somalia",
  za: "South Africa",
  ss: "South Sudan",
  es: "Spain",
  lk: "Sri Lanka",
  sd: "Sudan",
  sr: "Suriname",
  se: "Sweden",
  ch: "Switzerland",
  sy: "Syria",
  tw: "Taiwan",
  tj: "Tajikistan",
  tz: "Tanzania",
  th: "Thailand",
  tl: "Timor-Leste",
  tg: "Togo",
  to: "Tonga",
  tt: "Trinidad and Tobago",
  tn: "Tunisia",
  tr: "Turkey",
  tm: "Turkmenistan",
  tv: "Tuvalu",
  ug: "Uganda",
  ua: "Ukraine",
  ae: "United Arab Emirates",
  gb: "United Kingdom",
  us: "United States",
  uy: "Uruguay",
  uz: "Uzbekistan",
  vu: "Vanuatu",
  va: "Vatican City",
  ve: "Venezuela",
  vn: "Vietnam",
  ye: "Yemen",
  zm: "Zambia",
  zw: "Zimbabwe",
  usa: "United States",
  uk: "United Kingdom",
  uae: "United Arab Emirates",
  gbr: "United Kingdom",
  ind: "India",
  aus: "Australia",
  can: "Canada",
  deu: "Germany",
  fra: "France",
  jpn: "Japan",
  chn: "China",
  bra: "Brazil",
  rus: "Russia",
  kor: "Korea, South",
  zaf: "South Africa",
  nga: "Nigeria",
  egy: "Egypt",
  sau: "Saudi Arabia",
  are: "United Arab Emirates",
  bgd: "Bangladesh",
  pak: "Pakistan",
  idn: "Indonesia",
  mys: "Malaysia",
  sgp: "Singapore",
  phl: "Philippines",
  vnm: "Vietnam",
  tha: "Thailand",
  tur: "Turkey",
  irn: "Iran",
  irq: "Iraq",
  isr: "Israel",
  pol: "Poland",
  nld: "Netherlands",
  swe: "Sweden",
  nor: "Norway",
  dnk: "Denmark",
  fin: "Finland",
  che: "Switzerland",
  aut: "Austria",
  bel: "Belgium",
  prt: "Portugal",
  esp: "Spain",
  ita: "Italy",
  mex: "Mexico",
  arg: "Argentina",
  col: "Colombia",
  chl: "Chile",
  per: "Peru",
  nzl: "New Zealand",
};

export const jobTitleAbbreviations = {
  swe: "Software Engineer",
  sde: "Software Engineer",
  se: "Software Engineer",
  wd: "Web Developer",
  ds: "Data Scientist",
  sa: "Systems Analyst",
  na: "Network Administrator",
  itss: "IT Support Specialist",
  doe: "DevOps Engineer",
  dba: "Database Administrator",
  uxui: "UX/UI Designer",
  ux: "UX/UI Designer",
  ui: "UX/UI Designer",
  pm: "Product Manager",
  pjmm: "Project Manager",
  ba: "Business Analyst",
  om: "Operations Manager",
  mm: "Marketing Manager",
  sr: "Sales Representative",
  hrm: "Human Resources Manager",
  fa: "Financial Analyst",
  am: "Account Manager",
  ea: "Executive Assistant",
  csr: "Customer Service Representative",
  rn: "Registered Nurse",
  md: ["Medical Doctor", "Managing Director"],
  pa: "Physician Assistant",
  cpo: "Chief Product Officer",
  cfo: "Chief Financial Officer",
  ceo: "Chief Executive Officer",
  coo: "Chief Operations Officer",
  cto: "Chief Technology Officer",
  cmo: "Chief Marketing Officer",
  chro: "Chief Human Resources Officer",
  cio: "Chief Information Officer",
  gd: "Graphic Designer",
  cw: "Content Writer",
  smm: "Social Media Manager",
  ad: "Art Director",
  prs: "Public Relations Specialist",
  me: "Mechanical Engineer",
  ee: "Electrical Engineer",
  ce: "Civil Engineer",
  che: "Chemical Engineer",
  ae: "Aerospace Engineer",
  ie: "Industrial Engineer",
  bdm: "Business Development Manager",
  scm: "Supply Chain Manager",
  pd: "Product Designer",
  dm: "Digital Marketer",
  seo: "SEO Specialist",
  cs: "Content Strategist",
  ep: "Event Planner",
  la: "Legal Assistant",
  co: "Compliance Officer",
  rs: "Research Scientist",
  fe: "Front-End Developer",
  be: "Back-End Developer",
  fs: "Full-Stack Developer",
  bc: "Blockchain Developer",
  da: "Data Analyst",
  bia: "Business Intelligence Analyst",
  erpc: "ERP Consultant",
  itm: "IT Manager",
  ca: "Cybersecurity Analyst",
  tw: "Technical Writer",
  cp: "Computer Programmer",
  sa2: "Systems Administrator",
  ne: "Network Engineer",
  qae: "Quality Assurance Engineer",
  po: "Product Owner",
  csm: "Customer Success Manager",
  saleseng: "Sales Engineer",
  affmg: "Affiliate Marketing Manager",
  pmm: "Product Marketing Manager",
  dcc: "Digital Content Creator",
  cd: "Creative Director",
  bm: "Brand Manager",
  ae2: "Account Executive",
  re: "Regional Manager",
  nsm: "National Sales Manager",
  lc: "Legal Counsel",
  cl: "Corporate Lawyer",
  pata: "Patent Attorney",
  reb: "Real Estate Broker",
  ib: "Insurance Broker",
  ia: "Investment Analyst",
  mc: "Management Consultant",
  oa: "Operations Analyst",
  pc: "Project Coordinator",
  pgm: "Program Manager",
  lm: "Logistics Manager",
  sca: "Supply Chain Analyst",
  qci: "Quality Control Inspector",
  pde: "Product Development Engineer",
  hdm: "Help Desk Manager",
  itd: "IT Director",
  bsa: "Business Systems Analyst",
  tas: "Talent Acquisition Specialist",
  rec: "Recruiter",
  hrg: "HR Generalist",
  erpm: "Employee Relations Manager",
  hse: "Health and Safety Specialist",
  envs: "Environmental Scientist",
  fot: "Fitness Trainer",
  id: "Interior Designer",
  fd: "Fashion Designer",
  gd2: "Game Developer",
  ce2: "Cloud Engineer",
};

export const jobTitle = [
  "Software Engineer",
  "Web Developer",
  "Data Scientist",
  "Systems Analyst",
  "Network Administrator",
  "IT Support Specialist",
  "DevOps Engineer",
  "Database Administrator",
  "UX/UI Designer",
  "Product Manager",
  "Project Manager",
  "Business Analyst",
  "Operations Manager",
  "Marketing Manager",
  "Sales Representative",
  "Human Resources Manager",
  "Financial Analyst",
  "Account Manager",
  "Executive Assistant",
  "Customer Service Representative",
  "Registered Nurse",
  "Medical Doctor",
  "Physician Assistant",
  "Pharmacist",
  "Medical Technologist",
  "Health Administrator",
  "Physical Therapist",
  "Clinical Psychologist",
  "Radiologic Technologist",
  "Healthcare Consultant",
  "Teacher",
  "School Counselor",
  "Principal",
  "Educational Coordinator",
  "Librarian",
  "Instructional Designer",
  "Special Education Teacher",
  "Academic Advisor",
  "Curriculum Developer",
  "College Professor",
  "Graphic Designer",
  "Content Writer",
  "Editor",
  "Photographer",
  "Video Producer",
  "Marketing Specialist",
  "Social Media Manager",
  "Art Director",
  "Public Relations Specialist",
  "Copywriter",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Civil Engineer",
  "Chemical Engineer",
  "Aerospace Engineer",
  "Industrial Engineer",
  "Structural Engineer",
  "Environmental Engineer",
  "Systems Engineer",
  "Accountant",
  "Financial Planner",
  "Investment Banker",
  "Auditor",
  "Tax Specialist",
  "Credit Analyst",
  "Portfolio Manager",
  "Risk Manager",
  "Financial Advisor",
  "Controller",
  "Business Development Manager",
  "Supply Chain Manager",
  "Product Designer",
  "Digital Marketer",
  "SEO Specialist",
  "Content Strategist",
  "Event Planner",
  "Legal Assistant",
  "Paralegal",
  "Compliance Officer",
  "Insurance Underwriter",
  "Claims Adjuster",
  "Real Estate Agent",
  "Property Manager",
  "Construction Manager",
  "Architect",
  "Urban Planner",
  "Research Scientist",
  "Laboratory Technician",
  "Health and Safety Specialist",
  "Environmental Scientist",
  "Public Health Administrator",
  "Nonprofit Manager",
  "Volunteer Coordinator",
  "Fundraising Manager",
  "Catering Manager",
  "Restaurant Manager",
  "Hotel Manager",
  "Travel Agent",
  "Tour Guide",
  "Fitness Trainer",
  "Personal Chef",
  "Interior Designer",
  "Fashion Designer",
  "Textile Designer",
  "Jewelry Designer",
  "Art Curator",
  "Museum Director",
  "Exhibit Designer",
  "Stage Manager",
  "Lighting Designer",
  "Sound Engineer",
  "Music Producer",
  "Game Developer",
  "Cloud Engineer",
  "Front-End Developer",
  "Back-End Developer",
  "Full-Stack Developer",
  "Blockchain Developer",
  "Data Analyst",
  "Business Intelligence Analyst",
  "ERP Consultant",
  "IT Manager",
  "Cybersecurity Analyst",
  "Web Designer",
  "Technical Writer",
  "Computer Programmer",
  "Systems Administrator",
  "Network Engineer",
  "Quality Assurance Engineer",
  "Product Owner",
  "Customer Success Manager",
  "Sales Engineer",
  "Affiliate Marketing Manager",
  "Product Marketing Manager",
  "Digital Content Creator",
  "Copy Editor",
  "Creative Director",
  "Media Planner",
  "Brand Manager",
  "Market Research Analyst",
  "Advertising Manager",
  "Public Affairs Specialist",
  "Lobbyist",
  "E-commerce Manager",
  "Online Community Manager",
  "Influencer Marketing Manager",
  "Account Executive",
  "Regional Manager",
  "National Sales Manager",
  "Chief Financial Officer",
  "Chief Executive Officer",
  "Chief Operations Officer",
  "Chief Technology Officer",
  "Chief Marketing Officer",
  "Chief Human Resources Officer",
  "Chief Information Officer",
  "Legal Counsel",
  "Corporate Lawyer",
  "Patent Attorney",
  "Real Estate Broker",
  "Real Estate Appraiser",
  "Mortgage Broker",
  "Insurance Broker",
  "Claims Examiner",
  "Risk Analyst",
  "Investment Analyst",
  "Trading Specialist",
  "Credit Controller",
  "Tax Advisor",
  "Payroll Specialist",
  "Cost Accountant",
  "Management Consultant",
  "Operations Analyst",
  "Project Coordinator",
  "Program Manager",
  "Strategic Planner",
  "Logistics Manager",
  "Warehouse Manager",
  "Supply Chain Analyst",
  "Procurement Specialist",
  "Inventory Controller",
  "Distribution Manager",
  "Fleet Manager",
  "Facility Manager",
  "Maintenance Supervisor",
  "Construction Estimator",
  "Site Supervisor",
  "Safety Coordinator",
  "Quality Control Inspector",
  "Environmental Health Specialist",
  "Industrial Hygienist",
  "Manufacturing Engineer",
  "Production Planner",
  "Process Engineer",
  "Product Manager",
  "Product Development Engineer",
  "Field Service Technician",
  "Technical Support Specialist",
  "Help Desk Technician",
  "Customer Service Manager",
  "Call Center Manager",
  "Help Desk Manager",
  "IT Director",
  "Business Systems Analyst",
  "Change Management Specialist",
  "Process Improvement Consultant",
  "Organizational Development Consultant",
  "Training Specialist",
  "Instructional Coordinator",
  "Learning and Development Manager",
  "Talent Acquisition Specialist",
  "Recruiter",
  "HR Generalist",
  "HR Coordinator",
  "Employee Relations Manager",
  "Compensation and Benefits Specialist",
  "Payroll Manager",
  "Labor Relations Specialist",
  "Workforce Planning Analyst",
  "Diversity and Inclusion Specialist",
  "Organizational Development Manager",
  "Wellness Coordinator",
  "Health and Wellness Specialist",
  "Lifestyle Coach",
  "Nutritionist",
  "Dietitian",
  "Personal Trainer",
  "Sports Coach",
  "Athletic Trainer",
  "Outdoor Educator",
  "Park Ranger",
  "Environmental Educator",
  "Marine Biologist",
  "Wildlife Biologist",
  "Ecologist",
  "Conservation Scientist",
  "Forester",
  "Agricultural Scientist",
  "Soil Scientist",
  "Hydrologist",
  "Climate Scientist",
  "Energy Analyst",
  "Renewable Energy Engineer",
  "Sustainability Consultant",
  "Urban Designer",
  "Landscape Architect",
  "Construction Laborer",
  "Carpenter",
  "Electrician",
  "Plumber",
  "HVAC Technician",
  "Painter",
  "Drywall Installer",
  "Bricklayer",
  "Roofer",
  "Ironworker",
  "Sheet Metal Worker",
  "Glazier",
  "Tile Setter",
  "Concrete Finisher",
  "Pest Control Technician",
  "Security Guard",
  "Private Investigator",
  "Forensic Scientist",
  "Criminal Investigator",
  "Crime Scene Technician",
  "Corrections Officer",
  "Probation Officer",
  "Bailiff",
  "Court Clerk",
  "Parole Officer",
  "Family Therapist",
  "Marriage Counselor",
  "Mental Health Counselor",
  "Substance Abuse Counselor",
  "Social Worker",
  "Case Manager",
  "Community Service Manager",
  "Rehabilitation Counselor",
  "Addiction Counselor",
  "Clinical Social Worker",
  "School Social Worker",
  "Medical Social Worker",
  "Public Health Nurse",
  "Health Educator",
  "Clinical Research Coordinator",
  "Clinical Research Associate",
  "Pharmaceutical Sales Representative",
  "Medical Sales Representative",
  "Biotech Sales Representative",
  "Medical Device Sales Representative",
  "Healthcare Sales Manager",
  "Healthcare Recruiter",
  "Healthcare Administrator",
  "Hospital Administrator",
  "Clinic Manager",
  "Medical Office Manager",
  "Medical Billing Specialist",
  "Medical Coder",
  "Health Information Technician",
  "Medical Transcriptionist",
  "Medical Records Technician",
  "Health Information Manager",
  "Infection Control Specialist",
  "Medical Laboratory Technician",
  "Phlebotomist",
  "Optician",
  "Optometrist",
  "Audiologist",
  "Speech-Language Pathologist",
  "Occupational Therapist",
  "Rehabilitation Specialist",
  "Respiratory Therapist",
  "Dental Hygienist",
  "Dental Assistant",
  "Orthodontic Assistant",
  "Periodontist",
  "Endodontist",
  "Oral Surgeon",
  "Prosthodontist",
  "Pediatric Dentist",
  "Veterinarian",
  "Veterinary Technician",
  "Animal Caretaker",
  "Zoologist",
  "Marine Veterinarian",
  "Wildlife Rehabilitator",
  "Pet Groomer",
  "Pet Trainer",
  "Kennel Technician",
  "Equine Veterinarian",
  "Farm Manager",
  "Agronomist",
  "Crop Consultant",
  "Horticulturist",
  "Nursery Manager",
  "Greenhouse Manager",
  "Landscaper",
  "Tree Surgeon",
  "Arborist",
  "Groundskeeper",
  "Pest Management Specialist",
  "Irrigation Technician",
  "Soil Conservationist",
  "Water Resource Specialist",
  "Land Use Planner",
  "Urban Planner",
  "Regional Planner",
  "Transportation Planner",
  "Historic Preservationist",
  "City Planner",
  "Community Planner",
  "Rural Planner",
  "Site Planner",
  "Economic Development Specialist",
  "Housing Specialist",
  "Real Estate Appraiser",
  "Property Inspector",
  "Building Inspector",
  "Energy Auditor",
  "Certified Public Accountant",
  "Management Accountant",
  "Forensic Accountant",
  "Financial Controller",
  "Accounting Clerk",
  "Accounts Payable Clerk",
  "Accounts Receivable Clerk",
  "Bookkeeper",
  "Financial Advisor",
  "Investment Advisor",
  "Insurance Agent",
  "Mortgage Loan Officer",
  "Financial Planner",
  "Trust Officer",
  "Estate Planner",
  "Tax Consultant",
  "Treasury Analyst",
  "Cash Manager",
  "Credit Manager",
  "Risk Manager",
  "Compliance Manager",
  "Regulatory Affairs Specialist",
  "Legal Compliance Specialist",
  "Corporate Governance Specialist",
  "Ethics Officer",
  "Internal Auditor",
  "External Auditor",
  "Information Security Analyst",
  "Data Privacy Officer",
  "Cybersecurity Consultant",
  "Network Security Engineer",
  "IT Security Manager",
  "Penetration Tester",
  "Ethical Hacker",
  "Digital Forensics Analyst",
  "Systems Security Administrator",
  "Business Continuity Manager",
  "Disaster Recovery Specialist",
  "IT Risk Analyst",
  "Cloud Security Specialist",
  "Cloud Solutions Architect",
  "DevSecOps Engineer",
  "Blockchain Architect",
  "AI Engineer",
  "Machine Learning Engineer",
  "Robotics Engineer",
  "Automation Engineer",
  "Virtual Reality Developer",
  "Augmented Reality Developer",
  "IoT Solutions Architect",
  "Big Data Engineer",
  "Data Engineer",
  "Database Developer",
  "Database Manager",
  "Data Warehouse Specialist",
  "Data Migration Specialist",
  "ETL Developer",
  "Business Systems Developer",
  "Application Support Analyst",
  "System Integration Specialist",
  "Business Intelligence Developer",
  "Analytics Consultant",
  "Predictive Analyst",
  "Quantitative Analyst",
  "Statistician",
  "Operations Research Analyst",
  "Economist",
  "Market Research Analyst",
  "Sales Operations Analyst",
  "Customer Insights Analyst",
  "Customer Experience Manager",
  "Service Delivery Manager",
  "Client Relationship Manager",
  "Vendor Manager",
  "Supplier Quality Engineer",
  "Quality Assurance Analyst",
  "Quality Assurance Manager",
  "Testing Specialist",
  "Software Tester",
  "Test Engineer",
  "User Researcher",
  "User Experience Researcher",
  "Human Factors Engineer",
  "Accessibility Specialist",
  "Interaction Designer",
  "Product Tester",
  "Product Quality Manager",
  "Regulatory Compliance Manager",
  "Clinical Data Manager",
  "Medical Affairs Specialist",
  "Health Informatics Specialist",
  "Pharmaceutical Research Scientist",
  "Biostatistician",
  "Epidemiologist",
  "Genetic Counselor",
  "Biotechnology Technician",
  "Clinical Trials Manager",
  "Clinical Study Coordinator",
  "Clinical Operations Manager",
  "Medical Science Liaison",
  "Healthcare IT Specialist",
  "Healthcare Consultant",
  "Healthcare Analyst",
  "Telemedicine Specialist",
  "Health IT Project Manager",
  "Medical Device Engineer",
  "Pharmaceutical Sales Manager",
  "Medical Device Sales Manager",
  "Biotech Sales Manager",
  "Pharmaceutical Marketing Manager",
  "Medical Device Marketing Manager",
  "Biotech Marketing Manager",
  "Healthcare Marketing Manager",
  "Pharmaceutical Development Manager",
  "Medical Device Development Manager",
  "Biotech Development Manager",
  "Clinical Research Scientist",
  "Clinical Development Director",
  "Pharmaceutical Development Director",
  "Medical Device Development Director",
  "Biotech Development Director",
  "Healthcare Development Director",
  "Pharmaceutical Operations Manager",
  "Medical Device Operations Manager",
  "Biotech Operations Manager",
  "Healthcare Operations Manager",
  "Pharmaceutical Quality Manager",
  "Medical Device Quality Manager",
  "Biotech Quality Manager",
  "Healthcare Quality Manager",
  "Pharmaceutical Regulatory Affairs Manager",
  "Medical Device Regulatory Affairs Manager",
  "Biotech Regulatory Affairs Manager",
  "Healthcare Regulatory Affairs Manager",
  "Pharmaceutical Safety Manager",
  "Medical Device Safety Manager",
  "Biotech Safety Manager",
  "Healthcare Safety Manager",
  "Pharmaceutical Compliance Manager",
  "Medical Device Compliance Manager",
  "Biotech Compliance Manager",
  "Healthcare Compliance Manager",
  "Pharmaceutical Strategy Manager",
  "Medical Device Strategy Manager",
  "Biotech Strategy Manager",
  "Healthcare Strategy Manager",
  "Pharmaceutical Business Development Manager",
  "Medical Device Business Development Manager",
  "Biotech Business Development Manager",
  "Healthcare Business Development Manager",
  "Pharmaceutical Partnership Manager",
  "Medical Device Partnership Manager",
  "Biotech Partnership Manager",
  "Healthcare Partnership Manager",
  "Pharmaceutical Licensing Manager",
  "Medical Device Licensing Manager",
  "Biotech Licensing Manager",
  "Healthcare Licensing Manager",
  "Pharmaceutical Technology Manager",
  "Medical Device Technology Manager",
  "Biotech Technology Manager",
  "Healthcare Technology Manager",
  "Pharmaceutical Innovation Manager",
  "Medical Device Innovation Manager",
  "Biotech Innovation Manager",
  "Healthcare Innovation Manager",
  "Pharmaceutical Portfolio Manager",
  "Medical Device Portfolio Manager",
  "Biotech Portfolio Manager",
  "Healthcare Portfolio Manager",
  "Pharmaceutical Project Manager",
  "Medical Device Project Manager",
  "Biotech Project Manager",
  "Healthcare Project Manager",
  "Pharmaceutical Program Manager",
  "Medical Device Program Manager",
  "Biotech Program Manager",
  "Healthcare Program Manager",
  "Pharmaceutical Process Improvement Manager",
  "Medical Device Process Improvement Manager",
  "Biotech Process Improvement Manager",
  "Healthcare Process Improvement Manager",
  "Pharmaceutical Change Manager",
  "Medical Device Change Manager",
  "Biotech Change Manager",
  "Healthcare Change Manager",
  "Pharmaceutical Risk Manager",
  "Medical Device Risk Manager",
  "Biotech Risk Manager",
  "Healthcare Risk Manager",
  "Pharmaceutical Performance Manager",
  "Medical Device Performance Manager",
  "Biotech Performance Manager",
  "Healthcare Performance Manager",
  "Pharmaceutical Supply Chain Manager",
  "Medical Device Supply Chain Manager",
  "Biotech Supply Chain Manager",
  "Healthcare Supply Chain Manager",
  "Pharmaceutical Inventory Manager",
  "Medical Device Inventory Manager",
  "Biotech Inventory Manager",
  "Healthcare Inventory Manager",
  "Pharmaceutical Distribution Manager",
  "Medical Device Distribution Manager",
  "Biotech Distribution Manager",
  "Healthcare Distribution Manager",
  "Pharmaceutical Logistics Manager",
  "Medical Device Logistics Manager",
  "Biotech Logistics Manager",
  "Healthcare Logistics Manager",
  "Pharmaceutical Warehouse Manager",
  "Medical Device Warehouse Manager",
  "Biotech Warehouse Manager",
  "Healthcare Warehouse Manager",
  "Pharmaceutical Fleet Manager",
  "Medical Device Fleet Manager",
  "Biotech Fleet Manager",
  "Healthcare Fleet Manager",
  "Pharmaceutical Facility Manager",
  "Medical Device Facility Manager",
  "Biotech Facility Manager",
  "Healthcare Facility Manager",
  "Pharmaceutical Maintenance Manager",
  "Medical Device Maintenance Manager",
  "Biotech Maintenance Manager",
  "Healthcare Maintenance Manager",
  "Pharmaceutical Equipment Manager",
  "Medical Device Equipment Manager",
  "Biotech Equipment Manager",
  "Healthcare Equipment Manager",
  "Pharmaceutical Safety Manager",
  "Medical Device Safety Manager",
  "Biotech Safety Manager",
  "Healthcare Safety Manager",
  "Pharmaceutical Quality Control Manager",
  "Medical Device Quality Control Manager",
  "Biotech Quality Control Manager",
  "Healthcare Quality Control Manager",
  "Pharmaceutical Clinical Operations Manager",
  "Medical Device Clinical Operations Manager",
  "Biotech Clinical Operations Manager",
  "Healthcare Clinical Operations Manager",
  "Pharmaceutical Clinical Trials Manager",
  "Medical Device Clinical Trials Manager",
  "Biotech Clinical Trials Manager",
  "Healthcare Clinical Trials Manager",
  "Pharmaceutical Regulatory Manager",
  "Medical Device Regulatory Manager",
  "Biotech Regulatory Manager",
  "Healthcare Regulatory Manager",
  "Pharmaceutical Compliance Specialist",
  "Medical Device Compliance Specialist",
  "Biotech Compliance Specialist",
  "Healthcare Compliance Specialist",
  "Pharmaceutical Licensing Specialist",
  "Medical Device Licensing Specialist",
  "Biotech Licensing Specialist",
  "Healthcare Licensing Specialist",
  "Pharmaceutical Partnership Specialist",
  "Medical Device Partnership Specialist",
  "Biotech Partnership Specialist",
  "Healthcare Partnership Specialist",
  "Pharmaceutical Strategy Specialist",
  "Medical Device Strategy Specialist",
  "Biotech Strategy Specialist",
  "Healthcare Strategy Specialist",
  "Pharmaceutical Innovation Specialist",
  "Medical Device Innovation Specialist",
  "Biotech Innovation Specialist",
  "Healthcare Innovation Specialist",
  "Pharmaceutical Portfolio Specialist",
  "Medical Device Portfolio Specialist",
  "Biotech Portfolio Specialist",
  "Healthcare Portfolio Specialist",
  "Pharmaceutical Process Improvement Specialist",
  "Medical Device Process Improvement Specialist",
  "Biotech Process Improvement Specialist",
  "Healthcare Process Improvement Specialist",
  "Pharmaceutical Change Specialist",
  "Medical Device Change Specialist",
  "Biotech Change Specialist",
  "Healthcare Change Specialist",
  "Pharmaceutical Risk Specialist",
  "Medical Device Risk Specialist",
  "Biotech Risk Specialist",
  "Healthcare Risk Specialist",
  "Pharmaceutical Performance Specialist",
  "Medical Device Performance Specialist",
  "Biotech Performance Specialist",
  "Healthcare Performance Specialist",
  "Pharmaceutical Supply Chain Specialist",
  "Medical Device Supply Chain Specialist",
  "Biotech Supply Chain Specialist",
  "Healthcare Supply Chain Specialist",
  "Pharmaceutical Inventory Specialist",
  "Medical Device Inventory Specialist",
  "Biotech Inventory Specialist",
  "Healthcare Inventory Specialist",
  "Pharmaceutical Distribution Specialist",
  "Medical Device Distribution Specialist",
  "Biotech Distribution Specialist",
  "Healthcare Distribution Specialist",
  "Pharmaceutical Logistics Specialist",
  "Medical Device Logistics Specialist",
  "Biotech Logistics Specialist",
  "Healthcare Logistics Specialist",
  "Pharmaceutical Warehouse Specialist",
  "Medical Device Warehouse Specialist",
  "Biotech Warehouse Specialist",
  "Healthcare Warehouse Specialist",
  "Pharmaceutical Fleet Specialist",
  "Medical Device Fleet Specialist",
];

export const contactData = [
  {
    _id: 1,
    name: "John Doe",
    title: "Manager",
    company: "ABC Company",
    location: "USA",
    email: "5Ej9A@example.com",
    phone: "123-456-7890",
    employees: 10,
    industry: "Healthcare",
    keywords: ["Pharmaceutical", "Healthcare"],
  },
];

export const seniorityList = [
  "Owner",
  "Partner",
  "Chief Officer",
  "VP",
  "Director",
  "Senior",
  "Manager",
  "Intern",
  "Unpaid",
];

export const industryList = [
  "Accounting",
  "Airlines/Aviation",
  "Alternative Dispute Resolution",
  "Animation",
  "Apparel & Fashion",
  "Architecture & Planning",
  "Arts and Crafts",
  "Automotive",
  "Aviation & Aerospace",
  "Banking",
  "Biotechnology",
  "Broadcast Media",
  "Building Materials",
  "Business Supplies and Equipment",
  "Capital Markets",
  "Chemicals",
  "Civic & Social Organization",
  "Civil Engineering",
  "Commercial Real Estate",
  "Computer & Network Security",
  "Computer Games",
  "Computer Hardware",
  "Computer Networking",
  "Computer Software",
  "Construction",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Services",
  "Copywriting",
  "Design",
  "E-Learning",
  "Education Management",
  "Electrical/Electronic Manufacturing",
  "Entertainment",
  "Environmental Services",
  "Events Services",
  "Executive Office",
  "Facilities Services",
  "Farming",
  "Financial Services",
  "Fine Art",
  "Fishery",
  "Food & Beverages",
  "Food Production",
  "Fundraising",
  "Gambling & Casinos",
  "Glass, Ceramics & Concrete",
  "Government Administration",
  "Graphic Design",
  "Health, Wellness & Fitness",
  "Higher Education",
  "Hospital & Health Care",
  "Hospitality",
  "Human Resources",
  "Import & Export",
  "Individual & Family Services",
  "Industrial Automation",
  "Information Services",
  "Information Technology & Services",
  "Insurance",
  "International Trade & Development",
  "Internet",
  "Investment Banking",
  "Investment Management",
  "Judiciary",
  "Law Enforcement",
  "Legal Services",
  "Libraries",
  "Logistics and Supply Chain",
  "Luxury Goods & Jewelry",
  "Machinery",
  "Management Consulting",
  "Maritime",
  "Market Research",
  "Marketing & Advertising",
  "Mechanical or Industrial Engineering",
  "Media Production",
  "Medical Devices",
  "Mental Health Care",
  "Mining & Metals",
  "Motion Pictures and Film",
  "Museums and Institutions",
  "Music",
  "Nanotechnology",
  "Newspapers",
  "Non-Profit Organization Management",
  "Oil & Energy",
  "Online Publishing",
  "Outsourcing/Offshoring",
  "Package/Freight Delivery",
  "Paper & Forest Products",
  "Performing Arts",
  "Pharmaceuticals",
  "Philanthropy",
  "Photography",
  "Plastics",
  "Political Organization",
  "Primary/Secondary Education",
  "Printing",
  "Professional Training & Coaching",
  "Public Policy",
  "Public Relations & Communications",
  "Publishing",
  "Railroad Manufacture",
  "Ranching",
  "Real Estate",
  "Recreational Facilities and Services",
  "Religious Institutions",
  "Renewables & Environment",
  "Research",
  "Restaurants",
  "Retail",
  "Security & Investigations",
  "Semiconductors",
  "Shipbuilding",
  "Sports",
  "Staffing & Recruiting",
  "Supermarkets",
  "Telecommunications",
  "Textiles",
  "Transportation/Trucking/Railroad",
  "Utilities",
  "Venture Capital & Private Equity",
  "Veterinary",
  "Warehousing",
  "Wine and Spirits",
  "Wireless",
  "Writing and Editing",
  "3D Printing",
  "Acting",
  "Additive Manufacturing",
  "Agriculture",
  "Aging",
  "Aerospace Defense",
  "Aging Services",
  "Alternative Medicine",
  "Aviation Maintenance",
  "Behavioral Health",
  "Biomedicine",
  "Blockchain",
  "Broadcast Engineering",
  "Business Intelligence",
  "Clinical Research",
  "Cloud Services",
  "Corporate Finance",
  "Cultural Heritage",
  "Data Analysis",
  "Data Science",
  "Disaster Recovery",
  "EdTech",
  "Entertainment Technology",
  "Ethical Hacking",
  "Food Safety",
  "Genealogy",
  "Green Energy",
  "Health Informatics",
  "HR Tech",
  "Indoor Farming",
  "IoT",
  "Legal Tech",
  "Mergers & Acquisitions",
  "Music Technology",
  "Nuclear Medicine",
  "Pharmaceutical Research",
  "Public Health",
  "Renewable Resources",
  "Satellite Communications",
  "Smart Cities",
  "Sustainability",
  "Telemedicine",
  "Traditional Medicine",
  "Urban Planning",
  "Veterinary Services",
  "Wearable Technology",
  "Web Development",
];

export const industryAbbreviations = {
  it: "Information Technology & Services",
  itservices: "Information Technology & Services",
  hr: "Human Resources",
  rd: "Research",
  ma: "Mergers & Acquisitions",
  pr: "Public Relations & Communications",
  bi: "Business Intelligence",
  cpg: "Consumer Goods",
  fmcg: "Consumer Goods",
  fb: "Food & Beverages",
  pharma: "Pharmaceuticals",
  biotech: "Biotechnology",
  meddev: "Medical Devices",
  re: "Real Estate",
  vc: "Venture Capital & Private Equity",
  pe: "Venture Capital & Private Equity",
  scm: "Logistics and Supply Chain",
  gov: "Government Administration",
  npo: "Non-Profit Organization Management",
  edu: "Education Management",
  fin: "Financial Services",
  ins: "Insurance",
  telco: "Telecommunications",
  gaming: "Computer Games",
  legal: "Legal Services",
  health: "Hospital & Health Care",
  food: "Food & Beverages",
  retail: "Retail",
  construction: "Construction",
  energy: "Oil & Energy",
  mktg: "Marketing & Advertising",
  consulting: "Management Consulting",
  media: "Media Production",
  aero: "Aerospace Defense",
  mfg: "Mechanical or Industrial Engineering",
  oil: "Oil & Energy",
  gas: "Oil & Energy",
  pharmarc: "Pharmaceutical Research",
  biosc: "Biomedicine",
  ehs: "Environmental Services",
  med: "Medical Devices",
  ds: "Data Science",
  da: "Data Analysis",
  mlands: "Mergers & Acquisitions",
};

export const genderList = ["Male", "Female", "Unknown"];

export const emailStatusList = ["Verified", "Unavailable", "Extrapolated"];

export const employeeRange = [
  "1 - 10",
  "11 - 20",
  "21 - 50",
  "51 - 100",
  "101 - 200",
  "201 - 500",
  "501 - 1000",
  "1001 - 2000",
  "2001 - 5000",
  "5001 - 10000",
  "10001 and more",
];

export const revenueRange = [
  "0M - 0.1M",
  "0.1M - 0.5M",
  "0.5M - 1M",
  "1M - 5M",
  "5M - 10M",
  "10M - 25M",
  "25M - 50M",
  "50M - 100M",
  "100M - 500M",
  "500M - 1B",
  "1B - 5B",
  "5B - 10B",
  "10B and more",
];

export const stageList = ["Small", "Medium", "Large"];

export const emailTypeList = ["@gmail.com", "@yahoo.com", "@outlook.com"];
