import {
  MapPin,
  UserRoundSearch,
  BookUp2,
  Briefcase,
  Building2,
  Users,
  CircleDollarSign,
  MailQuestion,
  MailSearch,
  Calendar,
  MapPinHouse,
  MapPinned,
  List as ListIcon,
  Tag,
} from "lucide-react";

import {
  countryList,
  jobTitle,
  seniorityList,
  industryList,
  emailStatusList,
  employeeRange,
  revenueRange,
  emailTypeList,
} from "../../utils/data";

const filterList = (lists) => [
  {
    id: 1,
    label: "Country",
    optionsList: countryList,
    optionType: "countries",
    icon: MapPin,
    hasSearch: true,
  },
  {
    id: 2,
    label: "City / State",
    optionsList: [], // dynamically fetch from DB
    optionType: "city",
    icon: MapPinHouse,
    hasSearch: true,
  },
  {
    id: 3,
    label: "ZIP / Postal Code",
    optionsList: [], // dynamically fetch from DB
    optionType: "zip",
    icon: MapPinned,
    hasSearch: true,
  },
  {
    id: 4,
    label: "Job Title",
    optionsList: jobTitle,
    optionType: "jobTitle",
    icon: Briefcase,
    hasSearch: true,
  },
  {
    id: 5,
    label: "List",
    optionsList: lists,
    optionType: "list",
    icon: ListIcon,
    hasSearch: true,
  },
  {
    id: 6,
    label: "Industry",
    optionsList: industryList,
    optionType: "industry",
    icon: Building2,
    hasSearch: true,
  },
  {
    id: 16,
    label: "Keywords",
    optionsList: [],
    optionType: "keywords",
    icon: Tag,
    hasSearch: true,
  },
  {
    id: 7,
    label: "Seniority",
    optionsList: seniorityList,
    optionType: "seniority",
    icon: BookUp2,
    hasSearch: false,
  },
  {
    id: 8,
    label: "Name",
    optionsList: [],
    optionType: "personName",
    icon: UserRoundSearch,
    hasSearch: true,
  },
  {
    id: 10,
    label: "Employees",
    optionsList: employeeRange,
    optionType: "employeeRange",
    icon: Users,
    hasSearch: false,
  },
  {
    id: 11,
    label: "Annual Revenue",
    optionsList: revenueRange,
    optionType: "revenueRange",
    icon: CircleDollarSign,
    hasSearch: false,
  },
  {
    id: 12,
    label: "Email Status",
    optionsList: emailStatusList,
    optionType: "emailStatus",
    icon: MailQuestion,
    hasSearch: false,
  },
  {
    id: 13,
    label: "Email Type",
    optionsList: emailTypeList,
    optionType: "emailType",
    icon: MailSearch,
    hasSearch: false,
  },
  {
    id: 14,
    label: "Founded Year",
    optionsList: [],
    optionType: "foundedYear",
    icon: Calendar,
    hasSearch: false,
    hasYearFilter: true,
  },
  {
    id: 15,
    label: "Company Name",
    optionsList: [],
    optionType: "organizationName",
    icon: Building2,
    hasSearch: true,
  },
];

export default filterList;
